# Generated by Django 3.0.2 on 2020-01-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='employ',
            new_name='funcionario',
        ),
        migrations.RenameField(
            model_name='stockitems',
            old_name='stock',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='stockitems',
            old_name='product',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='stockitems',
            old_name='quantity',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='stockitems',
            old_name='sold',
            new_name='saldo',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='moviment',
        ),
        migrations.AddField(
            model_name='stock',
            name='movimento',
            field=models.CharField(choices=[('e', 'entrada'), ('s', 'saída')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='nf',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='nota fiscal'),
        ),
    ]
