# Generated by Django 3.0.3 on 2020-02-10 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200128_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='stock.Stock'),
        ),
    ]
