# Generated by Django 3.0.2 on 2020-01-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('produto',)},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='importad',
            new_name='importado',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='produto',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='estoque',
            field=models.IntegerField(default=1, verbose_name='estoque Atual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='estoque minimo'),
        ),
        migrations.AddField(
            model_name='product',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='preço'),
            preserve_default=False,
        ),
    ]
